# Generated by Django 5.2.8 on 2025-11-29 05:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['completed', 'position'],
            },
        ),
    ]
